services:
  expenseapp:
    build: 
      context: .
    container_name: expenseapp_cont
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/expenses_tracker?allowPublicKeyRetrieval=true&useSSL=false"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Test@123
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s  
    restart: always 
    ports:
      - 8080:8080
    networks:
      - mynewtwork

  mysql:
    image: mysql
    container_name: mysql_cont
    environment:
      MYSQL_DATABASE: expenses_tracker
      MYSQL_ROOT_PASSWORD: Test@123 
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - mynewtwork  
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pTest@123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  mynewtwork:

volumes:
  mysql-data:
